In [1]:
import pandas as pd
from yaml import safe_load
from tqdm import tqdm
import os

In [2]:
os.makedirs("batches", exist_ok=True)

In [4]:
filenames = []
for file in os.listdir('t20s'):
    filenames.append(os.path.join('t20s',file))

In [5]:
filenames[0:100]

['t20s\\1031665.yaml',
 't20s\\1034825.yaml',
 't20s\\1034827.yaml',
 't20s\\1034829.yaml',
 't20s\\1041615.yaml',
 't20s\\1041617.yaml',
 't20s\\1043989.yaml',
 't20s\\1043991.yaml',
 't20s\\1043993.yaml',
 't20s\\1044211.yaml',
 't20s\\1050217.yaml',
 't20s\\1050219.yaml',
 't20s\\1050221.yaml',
 't20s\\1050615.yaml',
 't20s\\1065348.yaml',
 't20s\\1072316.yaml',
 't20s\\1072317.yaml',
 't20s\\1072318.yaml',
 't20s\\1072319.yaml',
 't20s\\1072320.yaml',
 't20s\\1072321.yaml',
 't20s\\1072322.yaml',
 't20s\\1074957.yaml',
 't20s\\1074959.yaml',
 't20s\\1074961.yaml',
 't20s\\1074964.yaml',
 't20s\\1074965.yaml',
 't20s\\1074966.yaml',
 't20s\\1074968.yaml',
 't20s\\1074970.yaml',
 't20s\\1075507.yaml',
 't20s\\1075508.yaml',
 't20s\\1077947.yaml',
 't20s\\1077948.yaml',
 't20s\\1083449.yaml',
 't20s\\1083450.yaml',
 't20s\\1085495.yaml',
 't20s\\1085496.yaml',
 't20s\\1086067.yaml',
 't20s\\1086068.yaml',
 't20s\\1086069.yaml',
 't20s\\1089202.yaml',
 't20s\\1089203.yaml',
 't20s\\1089243.yaml',
 't20s\\1098211.yaml',
 't20s\\1109610.yaml',
 't20s\\1115798.yaml',
 't20s\\1115799.yaml',
 't20s\\1115800.yaml',
 't20s\\1115807.yaml',
 't20s\\1115808.yaml',
 't20s\\1115809.yaml',
 't20s\\1117821.yaml',
 't20s\\1117822.yaml',
 't20s\\1117824.yaml',
 't20s\\1119501.yaml',
 't20s\\1119502.yaml',
 't20s\\1119542.yaml',
 't20s\\1119543.yaml',
 't20s\\1119544.yaml',
 't20s\\1119545.yaml',
 't20s\\1120093.yaml',
 't20s\\1120094.yaml',
 't20s\\1120095.yaml',
 't20s\\1120291.yaml',
 't20s\\1120292.yaml',
 't20s\\1120293.yaml',
 't20s\\1122285.yaml',
 't20s\\1122286.yaml',
 't20s\\1122287.yaml',
 't20s\\1122729.yaml',
 't20s\\1122730.yaml',
 't20s\\1122731.yaml',
 't20s\\1122902.yaml',
 't20s\\1122908.yaml',
 't20s\\1122909.yaml',
 't20s\\1122910.yaml',
 't20s\\1123206.yaml',
 't20s\\1123207.yaml',
 't20s\\1123208.yaml',
 't20s\\1123209.yaml',
 't20s\\1123210.yaml',
 't20s\\1126720.yaml',
 't20s\\1126721.yaml',
 't20s\\1126722.yaml',
 't20s\\1126723.yaml',
 't20s\\1126724.yaml',
 't20s\\1126725.yaml',
 't20s\\1126726.yaml',
 't20s\\1127300.yaml',
 't20s\\1127301.yaml',
 't20s\\1130746.yaml',
 't20s\\1130747.yaml',
 't20s\\1131235.yaml',
 't20s\\1131236.yaml',
 't20s\\1131237.yaml',
 't20s\\1131238.yaml',
 't20s\\1131239.yaml',
 't20s\\1131240.yaml',
 't20s\\1131241.yaml']

In [6]:
from yaml import safe_load
import pandas as pd
from tqdm import tqdm
import os

batch = []
batch_num = 0
match_id = 0

for file in tqdm(filenames, desc="Extracting"):

    try:
        with open(file, "r", encoding="utf-8") as f:
            data = safe_load(f)

        if data is None:
            continue

        df = pd.json_normalize(data)

        df["match_id"] = match_id
        match_id += 1

        batch.append(df)

        # Save every 200 matches
        if len(batch) == 200:

            batch_df = pd.concat(batch, ignore_index=True)

            batch_df.to_pickle(
                f"batches/batch_{batch_num:03d}.pkl"
            )

            print(
                f"\nSaved batch {batch_num} "
                f"({len(batch_df)} rows)"
            )

            batch_num += 1
            batch = []

    except Exception as e:
        print(f"\nError in {file}")
        print(e)

# Save last partial batch
if batch:

    batch_df = pd.concat(batch, ignore_index=True)

    batch_df.to_pickle(
        f"batches/batch_{batch_num:03d}.pkl"
    )

    print(f"\nSaved final batch {batch_num}")

Extracting:   4%|▍         | 200/5328 [01:45<3:37:34,  2.55s/it]

Saved batch 0 (200 rows)

Extracting:   8%|▊         | 400/5328 [03:02<2:46:25,  2.03s/it]

Saved batch 1 (200 rows)

Extracting:  11%|█▏        | 601/5328 [03:41<1:29:07,  1.13s/it]

Saved batch 2 (200 rows)

Extracting:  15%|█▌        | 800/5328 [04:23<1:39:41,  1.32s/it]

Saved batch 3 (200 rows)

Extracting:  19%|█▉        | 1001/5328 [05:04<1:15:36,  1.05s/it]

Saved batch 4 (200 rows)

Extracting:  23%|██▎       | 1201/5328 [05:46<1:26:22,  1.26s/it]

Saved batch 5 (200 rows)

Extracting:  26%|██▋       | 1401/5328 [06:30<1:14:35,  1.14s/it]

Saved batch 6 (200 rows)

Extracting:  30%|███       | 1600/5328 [07:14<1:57:03,  1.88s/it]

Saved batch 7 (200 rows)

Extracting:  34%|███▍      | 1801/5328 [07:55<58:26,  1.01it/s]

Saved batch 8 (200 rows)

Extracting:  38%|███▊      | 2001/5328 [08:42<1:19:25,  1.43s/it]

Saved batch 9 (200 rows)

Extracting:  41%|████▏     | 2201/5328 [09:25<1:07:58,  1.30s/it]

Saved batch 10 (200 rows)

Extracting:  45%|████▌     | 2401/5328 [10:07<58:20,  1.20s/it]

Saved batch 11 (200 rows)

Extracting:  49%|████▉     | 2600/5328 [10:50<1:25:03,  1.87s/it]

Saved batch 12 (200 rows)

Extracting:  53%|█████▎    | 2801/5328 [11:32<47:04,  1.12s/it]

Saved batch 13 (200 rows)

Extracting:  56%|█████▋    | 3001/5328 [12:15<49:56,  1.29s/it]

Saved batch 14 (200 rows)

Extracting:  60%|██████    | 3201/5328 [12:59<45:31,  1.28s/it]

Saved batch 15 (200 rows)

Extracting:  64%|██████▍   | 3400/5328 [13:40<47:48,  1.49s/it]

Saved batch 16 (200 rows)

Extracting:  68%|██████▊   | 3600/5328 [14:22<49:50,  1.73s/it]

Saved batch 17 (200 rows)

Extracting:  71%|███████▏  | 3801/5328 [15:06<32:09,  1.26s/it]

Saved batch 18 (200 rows)

Extracting:  75%|███████▌  | 4000/5328 [15:49<35:20,  1.60s/it]

Saved batch 19 (200 rows)

Extracting:  79%|███████▉  | 4201/5328 [16:30<23:08,  1.23s/it]

Saved batch 20 (200 rows)

Extracting:  83%|████████▎ | 4401/5328 [17:11<16:20,  1.06s/it]

Saved batch 21 (200 rows)

Extracting:  86%|████████▋ | 4601/5328 [17:54<14:12,  1.17s/it]

Saved batch 22 (200 rows)

Extracting:  90%|█████████ | 4801/5328 [18:36<10:09,  1.16s/it]

Saved batch 23 (200 rows)

Extracting:  94%|█████████▍| 5001/5328 [19:17<03:16,  1.67it/s]

Saved batch 24 (200 rows)

Extracting:  98%|█████████▊| 5201/5328 [20:00<01:56,  1.09it/s]

Saved batch 25 (200 rows)

Extracting: 100%|██████████| 5328/5328 [20:25<00:00,  4.35it/s]

Error in t20s\README.txt

Saved final batch 26

In [7]:
import os

print(len(os.listdir("batches")))

27

In [8]:
test = pd.read_pickle("batches/batch_000.pkl")

print(test.shape)

(200, 874)

In [9]:
import pandas as pd
import glob

files = sorted(glob.glob("batches/*.pkl"))

parts = []

for f in files:
    parts.append(pd.read_pickle(f))

final_df = pd.concat(parts, ignore_index=True)

print(final_df.shape)

(5327, 8167)

In [10]:
final_df.to_pickle("final_df.pkl")

In [11]:
test_df = pd.read_pickle("final_df.pkl")

print(test_df.shape)

(5327, 8167)

In [12]:
test_df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5327 entries, 0 to 5326
Columns: 8167 entries, innings to info.registry.people.Hafiz Qaleem
dtypes: float64(5), int64(4), object(8158)
memory usage: 1.3 GB

In [13]:
test_df.sample()

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.match_type_number,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
3504,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.92,2025-04-14,1,6,Mong Kok,[2025-04-13],male,T20,3138.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
empty_cols = final_df.columns[final_df.isna().all()]

print("Completely empty columns:", len(empty_cols))
empty_cols[:20]

Completely empty columns: 0

Index([], dtype='object')

In [15]:
constant_cols = []

for col in final_df.columns:
    if final_df[col].nunique(dropna=False) == 1:
        constant_cols.append(col)

print("Constant columns:", len(constant_cols))
constant_cols[:50]

TypeError: unhashable type: 'list'

In [16]:
[col for col in final_df.columns if "registry.people" in col]

['info.registry.people.AD Hales',
 'info.registry.people.AG Wharf',
 'info.registry.people.AR Nurse',
 'info.registry.people.AU Rashid',
 'info.registry.people.CAK Walton',
 'info.registry.people.CH Gayle',
 'info.registry.people.CJ Jordan',
 'info.registry.people.CR Brathwaite',
 'info.registry.people.DJ Willey',
 'info.registry.people.E Lewis',
 'info.registry.people.EJG Morgan',
 'info.registry.people.J Srinath',
 'info.registry.people.JC Buttler',
 'info.registry.people.JE Root',
 'info.registry.people.JE Taylor',
 'info.registry.people.JJ Roy',
 'info.registry.people.JM Bairstow',
 'info.registry.people.JN Mohammed',
 'info.registry.people.KA Pollard',
 'info.registry.people.KOK Williams',
 'info.registry.people.LE Plunkett',
 'info.registry.people.MA Gough',
 'info.registry.people.MN Samuels',
 'info.registry.people.R Powell',
 'info.registry.people.RJ Bailey',
 'info.registry.people.RT Robinson',
 'info.registry.people.SP Narine',
 'info.registry.people.TK Curran',
 'info.registry.people.A Nehra',
 'info.registry.people.AJ Pycroft',
 'info.registry.people.AK Chaudhary',
 'info.registry.people.AY Dandekar',
 'info.registry.people.BA Stokes',
 'info.registry.people.CK Nandan',
 'info.registry.people.HH Pandya',
 'info.registry.people.JJ Bumrah',
 'info.registry.people.KL Rahul',
 'info.registry.people.MK Pandey',
 'info.registry.people.MM Ali',
 'info.registry.people.MS Dhoni',
 'info.registry.people.Nitin Menon',
 'info.registry.people.Parvez Rasool',
 'info.registry.people.SK Raina',
 'info.registry.people.SW Billings',
 'info.registry.people.TS Mills',
 'info.registry.people.V Kohli',
 'info.registry.people.YS Chahal',
 'info.registry.people.Yuvraj Singh',
 'info.registry.people.A Mishra',
 'info.registry.people.C Shamshuddin',
 'info.registry.people.LA Dawson',
 'info.registry.people.RR Pant',
 'info.registry.people.AD Russell',
 'info.registry.people.ADS Fletcher',
 'info.registry.people.AM Rahane',
 'info.registry.people.B Kumar',
 'info.registry.people.DJ Bravo',
 'info.registry.people.J Charles',
 'info.registry.people.JS Wilson',
 'info.registry.people.LMP Simmons',
 'info.registry.people.LS Reifer',
 'info.registry.people.Mohammed Shami',
 'info.registry.people.N Duguid',
 'info.registry.people.PA Gustard',
 'info.registry.people.R Ashwin',
 'info.registry.people.RA Jadeja',
 'info.registry.people.RG Sharma',
 'info.registry.people.RS Madugalle',
 'info.registry.people.S Badree',
 'info.registry.people.STR Binny',
 'info.registry.people.A Gardner',
 'info.registry.people.A Wellington',
 'info.registry.people.AE Satterthwaite',
 'info.registry.people.AJ Barrow',
 'info.registry.people.AJ Blackwell',
 'info.registry.people.AJ Healy',
 'info.registry.people.AM Peterson',
 'info.registry.people.BL Mooney',
 'info.registry.people.EC Perry',
 'info.registry.people.EJ Villani',
 'info.registry.people.EM Bermingham',
 'info.registry.people.GA Abood',
 'info.registry.people.HR Huddleston',
 'info.registry.people.JD Ward',
 'info.registry.people.JL Jonassen',
 'info.registry.people.KJ Martin',
 'info.registry.people.KM Beams',
 'info.registry.people.KT Perkins',
 'info.registry.people.LM Kasperek',
 'info.registry.people.LMM Tahuhu',
 'info.registry.people.M Strano',
 'info.registry.people.ML Schutt',
 'info.registry.people.MM Lanning',
 'info.registry.people.RH Priest',
 'info.registry.people.SAJ Craig',
 'info.registry.people.SR Bernard',
 'info.registry.people.SW Bates',
 'info.registry.people.ML Green',
 'info.registry.people.AC Kerr',
 'info.registry.people.AC Jayangani',
 'info.registry.people.BMSM Kumari',
 'info.registry.people.EA Osborne',
 'info.registry.people.EA Perry',
 'info.registry.people.GWHM Perera',
 'info.registry.people.HML Madushani',
 'info.registry.people.I Ranaweera',
 'info.registry.people.ID Gunawardene',
 'info.registry.people.JWHD Boteju',
 'info.registry.people.KADA Kanchana',
 'info.registry.people.KDU Prabodhani',
 'info.registry.people.LE Kaushalya',
 'info.registry.people.M Pethiyagoda',
 'info.registry.people.MADD Surangika',
 'info.registry.people.MGMCP Gunawardene',
 'info.registry.people.NE Bolton',
 'info.registry.people.PM Weerakkody',
 'info.registry.people.RM Farrell',
 'info.registry.people.SPD Jayamahamudali',
 'info.registry.people.Ahmed Shahab',
 'info.registry.people.Ahsan Raza',
 'info.registry.people.Babar Azam',
 'info.registry.people.Hasan Ali',
 'info.registry.people.Imad Wasim',
 'info.registry.people.Khalid Latif',
 'info.registry.people.Khalid Mahmood',
 'info.registry.people.Mohammad Nawaz (3)',
 'info.registry.people.N Pooran',
 'info.registry.people.Sarfraz Ahmed',
 'info.registry.people.Sharjeel Khan',
 'info.registry.people.Shoaib Malik',
 'info.registry.people.Shozab Raza',
 'info.registry.people.Sohail Tanvir',
 'info.registry.people.Umar Akmal',
 'info.registry.people.Wahab Riaz',
 'info.registry.people.Mohammad Amir',
 'info.registry.people.Rumman Raees',
 'info.registry.people.Aliya Riaz',
 'info.registry.people.Asmavia Iqbal',
 'info.registry.people.Ayesha Zafar',
 'info.registry.people.Bismah Maroof',
 'info.registry.people.D Venter',
 'info.registry.people.Iram Javed',
 'info.registry.people.Javeria Khan',
 'info.registry.people.K Cross',
 'info.registry.people.MJG Nielsen',
 'info.registry.people.Nain Abidi',
 'info.registry.people.Nida Dar',
 'info.registry.people.RE Hayward',
 'info.registry.people.SFM Devine',
 'info.registry.people.Sadia Yousuf',
 'info.registry.people.Sana Mir',
 'info.registry.people.Sidra Nawaz',
 'info.registry.people.TMM Newton',
 'info.registry.people.AA Patil',
 'info.registry.people.AK Rana',
 'info.registry.people.Anam Amin',
 'info.registry.people.BB Pradhan',
 'info.registry.people.E Bisht',
 'info.registry.people.GF Labrooy',
 'info.registry.people.H Kaur',
 'info.registry.people.J Goswami',
 'info.registry.people.M Raj',
 'info.registry.people.Preeti Bose',
 'info.registry.people.S Mandhana',
 'info.registry.people.S Meghana',
 'info.registry.people.S Pandey',
 'info.registry.people.S Verma',
 'info.registry.people.Sarika Prasad',
 'info.registry.people.V Krishnamurthy',
 'info.registry.people.A Zampa',
 'info.registry.people.AC Agar',
 'info.registry.people.AJ Tye',
 'info.registry.people.AT Carey',
 'info.registry.people.B Stanlake',
 'info.registry.people.C Munro',
 'info.registry.people.C de Grandhomme',
 'info.registry.people.CA Lynn',
 'info.registry.people.CM Brown',
 'info.registry.people.DA Warner',
 'info.registry.people.DJM Short',
 'info.registry.people.GJ Maxwell',
 'info.registry.people.IS Sodhi',
 'info.registry.people.KS Williamson',
 'info.registry.people.KW Richardson',
 'info.registry.people.LRPL Taylor',
 'info.registry.people.MJ Guptill',
 'info.registry.people.MJ Santner',
 'info.registry.people.MP Stoinis',
 'info.registry.people.SD Fry',
 'info.registry.people.SJ Nogajski',
 'info.registry.people.TA Blundell',
 'info.registry.people.TA Boult',
 'info.registry.people.TC Bruce',
 'info.registry.people.TG Southee',
 'info.registry.people.DJ Malan',
 'info.registry.people.MA Wood',
 'info.registry.people.TM Head',
 'info.registry.people.AJ Finch',
 'info.registry.people.JM Vince',
 'info.registry.people.MS Chapman',
 'info.registry.people.P Wilson',
 'info.registry.people.SB Haig',
 'info.registry.people.TL Seifert',
 'info.registry.people.WR Knights',
 'info.registry.people.BM Wheeler',
 'info.registry.people.AL Gillies',
 'info.registry.people.AJ Neill',
 'info.registry.people.Ahmed Shah Pakteen',
 'info.registry.people.Aizaz Khan',
 'info.registry.people.Anshuman Rath',
 'info.registry.people.BTJ Wheal',
 'info.registry.people.Babar Hayat',
 'info.registry.people.CD Wallace',
 'info.registry.people.CD de Lange',
 'info.registry.people.CS MacLeod',
 'info.registry.people.Ehsan Khan',
 'info.registry.people.Ehsan Nawaz',
 'info.registry.people.HG Munsey',
 'info.registry.people.Iftikhar Ali',
 'info.registry.people.JH Davey',
 'info.registry.people.KJ Coetzer',
 'info.registry.people.MH Cross',
 'info.registry.people.MRJ Watt',
 'info.registry.people.Nadeem Ahmed',
 'info.registry.people.Nizakat Khan',
 'info.registry.people.RD Berrington',
 'info.registry.people.SM Sharif',
 'info.registry.people.Shahid Wasif',
 'info.registry.people.Tanveer Ahmed',
 'info.registry.people.Waqas Barkat',
 'info.registry.people.Waqas Khan',
 'info.registry.people.A Poulose',
 'info.registry.people.AJT Dowdalls',
 'info.registry.people.AV Lalcheta',
 'info.registry.people.Ahsan Malik',
 'info.registry.people.Aqib Ilyas',
 'info.registry.people.BN Cooper',
 'info.registry.people.Bilal Khan',
 'info.registry.people.DT Jukes',
 'info.registry.people.Kaleemullah',
 'info.registry.people.Khawar Ali',
 'info.registry.people.Khurram Nawaz',
 'info.registry.people.MJG Rippon',
 "info.registry.people.MP O'Dowd",
 'info.registry.people.Mohammad Nadeem',
 'info.registry.people.Naseem Khushi',
 'info.registry.people.PA van Meekeren',
 'info.registry.people.PM Seelaar',
 'info.registry.people.PW Borren',
 'info.registry.people.RE van der Merwe',
 'info.registry.people.SJ Myburgh',
 'info.registry.people.Sultan Ahmed',
 'info.registry.people.T van der Gugten',
 'info.registry.people.Tabarak Dar',
 'info.registry.people.W Barresi',
 'info.registry.people.Zeeshan Maqsood',
 'info.registry.people.C Carter',
 'info.registry.people.Mehran Khan',
 'info.registry.people.TP Visee',
 'info.registry.people.AR McBrine',
 'info.registry.people.Ahmed Raza',
 'info.registry.people.Ahmed Shah Durrani',
 'info.registry.people.Amjad Javed',
 'info.registry.people.CA Young',
 'info.registry.people.GC Wilson',
 'info.registry.people.GH Dockrell',
 'info.registry.people.GJ Thompson',
 'info.registry.people.Ghulam Shabber',
 'info.registry.people.Imran Haider',
 'info.registry.people.J Mulder',
 "info.registry.people.KJ O'Brien",
 'info.registry.people.Mohammad Naveed',
 'info.registry.people.Mohammad Shahzad (2)',
 'info.registry.people.Muhammad Usman',
 'info.registry.people.PR Stirling',
 'info.registry.people.Rameez Shahzad',
 'info.registry.people.Rohan Mustafa',
 'info.registry.people.SW Poynter',
 'info.registry.people.Shaiman Anwar',
 'info.registry.people.WB Rankin',
 'info.registry.people.WTS Porterfield',
 'info.registry.people.Zahoor Khan',
 'info.registry.people.CB Sole',
 'info.registry.people.MA Leask',
 'info.registry.people.A Paleker',
 'info.registry.people.AB de Villiers',
 'info.registry.people.AL Phehlukwayo',
 'info.registry.people.AM Phangiso',
 'info.registry.people.AT Holdstock',
 'info.registry.people.BE Hendricks',
 'info.registry.people.BP Jele',
 'info.registry.people.D Paterson',
 'info.registry.people.DA Miller',
 'info.registry.people.F Behardien',
 'info.registry.people.HM Amla',
 'info.registry.people.Imrul Kayes',
 'info.registry.people.JP Duminy',
 'info.registry.people.Mahmudullah',
 'info.registry.people.Mehedi Hasan Miraz',
 'info.registry.people.Mohammad Saifuddin',
 'info.registry.people.Mushfiqur Rahim',
 'info.registry.people.Q de Kock',
 'info.registry.people.R Frylinck',
 'info.registry.people.Rubel Hossain',
 'info.registry.people.S George',
 'info.registry.people.Sabbir Rahman',
 'info.registry.people.Shafiul Islam',
 'info.registry.people.Shakib Al Hasan',
 'info.registry.people.Soumya Sarkar',
 'info.registry.people.Taskin Ahmed',
 'info.registry.people.D Pretorius',
 'info.registry.people.Liton Das',
 'info.registry.people.M Mosehle',
 'info.registry.people.Ahmed Shehzad',
 'info.registry.people.GO Brathwaite',
 'info.registry.people.JJ Crowe',
 'info.registry.people.JO Holder',
 'info.registry.people.Kamran Akmal',
 'info.registry.people.Mohammad Hafeez',
 'info.registry.people.Shadab Khan',
 'info.registry.people.Fakhar Zaman',
 'info.registry.people.CK Kapugedera',
 'info.registry.people.DAS Gunaratne',
 'info.registry.people.EMDY Munaweera',
 'info.registry.people.JRMVB Sanjaya',
 'info.registry.people.KMDN Kulasekara',
 'info.registry.people.MDKJ Perera',
 'info.registry.people.Mashrafe Mortaza',
 'info.registry.people.Mosaddek Hossain',
 'info.registry.people.Mustafizur Rahman',
 'info.registry.people.NLTC Perera',
 'info.registry.people.REJ Martinesz',
 'info.registry.people.RR Wimalasiri',
 'info.registry.people.RSA Palliyaguruge',
 'info.registry.people.S Prasanna',
 'info.registry.people.SL Malinga',
 'info.registry.people.TAM Siriwardana',
 'info.registry.people.Tamim Iqbal',
 'info.registry.people.WU Tharanga',
 'info.registry.people.WN de Silva',
 'info.registry.people.A Hartley',
 'info.registry.people.BC Treloar',
 'info.registry.people.D Hazell',
 'info.registry.people.DM Kimmince',
 'info.registry.people.DN Wyatt',
 'info.registry.people.FC Wilson',
 'info.registry.people.GC Joshua',
 'info.registry.people.HC Knight',
 'info.registry.people.JL Gunn',
 'info.registry.people.KH Brunt',
 'info.registry.people.NR Sciver',
 'info.registry.people.RL Haynes',
 'info.registry.people.S Ecclestone',
 'info.registry.people.SE Aley',
 'info.registry.people.SJ Taylor',
 'info.registry.people.TT Beaumont',
 'info.registry.people.A Shrubsole',
 'info.registry.people.SA Lightbody',
 'info.registry.people.A Nao',
 'info.registry.people.A Vala',
 'info.registry.people.Akbar Ali',
 'info.registry.people.IJ Dixon',
 'info.registry.people.JB Reva',
 'info.registry.people.JNT Vare',
 'info.registry.people.L Siaka',
 'info.registry.people.MD Dai',
 'info.registry.people.Mohammed Qasim',
 'info.registry.people.N Vanua',
 'info.registry.people.S Bau',
 'info.registry.people.Sultan Ahmed (2)',
 'info.registry.people.TP Ura',
 'info.registry.people.VV Morea',
 'info.registry.people.WT Gavera',
 'info.registry.people.CA Soper',
 'info.registry.people.Adnan Mufti',
 'info.registry.people.D Bau',
 'info.registry.people.L Sreekumar',
 'info.registry.people.DC Boon',
 'info.registry.people.KD Karthik',
 'info.registry.people.KM Jadhav',
 'info.registry.people.Kuldeep Yadav',
 'info.registry.people.S Dhawan',
 'info.registry.people.A Dananjaya',
 'info.registry.people.AD Mathews',
 'info.registry.people.AR Patel',
 'info.registry.people.I Udana',
 'info.registry.people.MD Shanaka',
 'info.registry.people.N Dickwella',
 'info.registry.people.SMA Priyanjan',
 'info.registry.people.AK Kitchen',
 'info.registry.people.DAJ Bracewell',
 'info.registry.people.GD Phillips',
 'info.registry.people.SD Hope',
 'info.registry.people.SHA Rance',
 'info.registry.people.A Mehrotra',
 'info.registry.people.SO Hetmyer',
 'info.registry.people.SS Cottrell',
 'info.registry.people.RR Emrit',
 'info.registry.people.Faheem Ashraf',
 'info.registry.people.Haris Sohail',
 'info.registry.people.RB Richardson',
 'info.registry.people.Umar Amin',
 'info.registry.people.Aamer Yamin',
 'info.registry.people.Aleem Dar',
 'info.registry.people.BCJ Cutting',
 'info.registry.people.DJG Sammy',
 'info.registry.people.F du Plessis',
 'info.registry.people.GD Elliott',
 'info.registry.people.Imran Tahir',
 'info.registry.people.M Morkel',
 'info.registry.people.Sohail Khan',
 'info.registry.people.TD Paine',
 'info.registry.people.Asif Yaqoob',
 'info.registry.people.PD Collingwood',
 'info.registry.people.Usman Shinwari',
 'info.registry.people.GJ Bailey',
 'info.registry.people.DT Christian',
 'info.registry.people.JP Behrendorff',
 'info.registry.people.MC Henriques',
 'info.registry.people.NM Coulter-Nile',
 'info.registry.people.MJ Swepson',
 'info.registry.people.UT Yadav',
 'info.registry.people.JT Ball',
 'info.registry.people.DL Chahar',
 'info.registry.people.S Kaul',
 'info.registry.people.BC Broad',
 'info.registry.people.HM Nicholls',
 'info.registry.people.SS Iyer',
 'info.registry.people.TWM Latham',
 'info.registry.people.AF Milne',
 'info.registry.people.Mohammed Siraj',
 'info.registry.people.MD Gunathilaka',
 'info.registry.people.ML Udawatte',
 'info.registry.people.S Samarawickrama',
 'info.registry.people.SS Pathirana',
 'info.registry.people.PC de Silva',
 'info.registry.people.Rashid Riaz',
 'info.registry.people.CH Morris',
 'info.registry.people.CJ Dala',
 'info.registry.people.H Klaasen',
 'info.registry.people.JD Unadkat',
 'info.registry.people.JT Smuts',
 'info.registry.people.RR Hendricks',
 'info.registry.people.T Shamsi',
 'info.registry.people.SN Thakur',
 'info.registry.people.C Jonker',
 'info.registry.people.MVT Fernando',
 'info.registry.people.N Pradeep',
 'info.registry.people.PVD Chameera',
 'info.registry.people.Washington Sundar',
 'info.registry.people.A Mohammed',
 'info.registry.people.AK Peters',
 'info.registry.people.ASS Fletcher',
 'info.registry.people.B Cooper',
 'info.registry.people.BYA Mendis',
 'info.registry.people.CM Tuckett',
 'info.registry.people.DJS Dottin',
 'info.registry.people.Denavon Hayles',
 'info.registry.people.HASD Siriwardene',
 'info.registry.people.HHC Gunaratne',
 'info.registry.people.HK Matthews',
 'info.registry.people.JM Williams',
 'info.registry.people.Kycia A Knight',
 'info.registry.people.Kyshona A Knight',
 'info.registry.people.MDN Hansika',
 'info.registry.people.MR Aguilleira',
 'info.registry.people.RS Vandort',
 'info.registry.people.SC Selman',
 'info.registry.people.SR Taylor',
 'info.registry.people.SS Weerakkody',
 'info.registry.people.Aiman Anwer',
 'info.registry.people.Mohammed Anees',
 'info.registry.people.Nahida Khan',
 'info.registry.people.Nashra Sandhu',
 'info.registry.people.Natalia Pervaiz',
 'info.registry.people.SRH Curtis',
 'info.registry.people.Sidra Ameen',
 'info.registry.people.HM Rowe',
 'info.registry.people.A Khaka',
 'info.registry.people.CL Tryon',
 'info.registry.people.D van Niekerk',
 'info.registry.people.GH Pienaar',
 'info.registry.people.JI Rodrigues',
 'info.registry.people.L Lee',
 'info.registry.people.LB Gcuma',
 'info.registry.people.M Daniels',
 'info.registry.people.M Kapp',
 'info.registry.people.M du Preez',
 'info.registry.people.N de Klerk',
 'info.registry.people.P Vastrakar',
 'info.registry.people.Poonam Yadav',
 'info.registry.people.R Ntozakhe',
 'info.registry.people.RP Yadav',
 'info.registry.people.S Ismail',
 'info.registry.people.S Luus',
 'info.registry.people.Siphelele Gasa',
 'info.registry.people.Stephen Harris',
 'info.registry.people.T Bhatia',
 'info.registry.people.M Klaas',
 'info.registry.people.PJ Vosloo',
 'info.registry.people.RS Gayakwad',
 'info.registry.people.S Wadvalla',
 'info.registry.people.DB Sharma',
 'info.registry.people.R Dhar',
 'info.registry.people.DJ Millns',
 'info.registry.people.HNK Jensen',
 'info.registry.people.JH Evans',
 'info.registry.people.L Wolvaardt',
 'info.registry.people.Lou Coulthard',
 'info.registry.people.Phil Whitticase',
 'info.registry.people.S Lackay',
 'info.registry.people.T Brits',
 'info.registry.people.Z Mali',
 'info.registry.people.AE Jones',
 'info.registry.people.MJ Saggers',
 'info.registry.people.B Bezuidenhout',
 'info.registry.people.NE Farrant',
 'info.registry.people.KE Ebrahim',
 'info.registry.people.NL Bainton',
 'info.registry.people.JM Watkin',
 'info.registry.people.KL George',
 'info.registry.people.Tom Lungley',
 'info.registry.people.AC Evans',
 'info.registry.people.Asif Ali',
 'info.registry.people.DA Haggo',
 'info.registry.people.DE Budge',
 'info.registry.people.Hamza Tahir',
 'info.registry.people.Hussain Talat',
 'info.registry.people.IN Ramage',
 'info.registry.people.Afif Hossain',
 'info.registry.people.Anisur Rahman',
 'info.registry.people.Ariful Haque',
 'info.registry.people.BKG Mendis',
 'info.registry.people.BMAJ Mendis',
 'info.registry.people.DSK Madushanka',
 'info.registry.people.LD Chandimal',
 'info.registry.people.Mahfuzur Rahman',
 'info.registry.people.Masudur Rahman',
 'info.registry.people.Nazmul Islam',
 'info.registry.people.Sharfuddoula',
 'info.registry.people.Zakir Hasan',
 'info.registry.people.Abu Jayed',
 'info.registry.people.Gazi Sohel',
 'info.registry.people.JDF Vandersay',
 'info.registry.people.MA Aponso',
 'info.registry.people.Mahedi Hasan',
 'info.registry.people.Mohammad Mithun',
 'info.registry.people.HAS Khalid',
 'info.registry.people.KN Ananthapadmanabhan',

In [17]:
cols_to_drop = [col for col in final_df.columns
                if 'registry.people' in col]

print("Columns to drop:", len(cols_to_drop))

final_df = final_df.drop(columns=cols_to_drop)

Columns to drop: 8029

In [19]:
final_df.shape

(5327, 138)

In [20]:
final_df.to_pickle("final_df_clean.pkl")

In [21]:
l = final_df.columns.tolist()

In [22]:
for i in l:
    print(i)

innings
meta.data_version
meta.created
meta.revision
info.balls_per_over
info.city
info.dates
info.gender
info.match_type
info.match_type_number
info.outcome.winner
info.outcome.by.runs
info.overs
info.player_of_match
info.players.West Indies
info.players.England
info.teams
info.toss.decision
info.toss.winner
info.umpires
info.venue
match_id
info.outcome.by.wickets
info.players.India
info.neutral_venue
info.outcome.result
info.players.Australia
info.players.New Zealand
info.outcome.method
info.players.Sri Lanka
info.players.Pakistan
info.players.Hong Kong
info.players.Scotland
info.players.Netherlands
info.players.Oman
info.players.Ireland
info.players.United Arab Emirates
info.players.South Africa
info.players.Bangladesh
info.players.Papua New Guinea
info.players.ICC World XI
info.players.Nepal
info.players.Zimbabwe
info.outcome.eliminator
info.players.Thailand
info.players.Uganda
info.players.Malaysia
info.players.Botswana
info.players.Lesotho
info.players.Malawi
info.players.Namibia
info.players.Sierra Leone
info.players.Mozambique
info.players.China
info.players.Kuwait
info.players.Philippines
info.players.Vanuatu
info.players.United States of America
info.players.Germany
info.players.Italy
info.players.Nigeria
info.players.Tanzania
info.players.Rwanda
info.players.Kenya
info.players.Japan
info.players.Indonesia
info.players.Fiji
info.players.Samoa
info.players.Canada
info.players.Ghana
info.players.Guernsey
info.players.Denmark
info.players.Norway
info.players.Jersey
info.players.Maldives
info.players.Mali
info.players.Singapore
info.players.Qatar
info.players.South Korea
info.players.Bermuda
info.players.Cayman Islands
info.players.Portugal
info.players.Spain
info.players.Gibraltar
info.players.Bhutan
info.players.Saudi Arabia
info.players.Bahrain
info.players.Iran
info.players.Austria
info.players.Belgium
info.players.Luxembourg
info.players.Czech Republic
info.players.Isle of Man
info.players.Bulgaria
info.players.Romania
info.players.Greece
info.players.Serbia
info.players.Malta
info.players.France
info.players.Sweden
info.players.Finland
info.players.Eswatini
info.players.Cameroon
info.players.Hungary
info.players.Estonia
info.players.Cyprus
info.players.Switzerland
info.players.Argentina
info.players.Brazil
info.players.Seychelles
info.players.Swaziland
info.players.Belize
info.players.Bahamas
info.players.Panama
info.players.Barbados
info.players.Israel
info.players.Turkey
info.players.Croatia
info.players.Slovenia
info.toss.uncontested
info.players.Cook Islands
info.players.St Helena
info.players.Gambia
info.players.Cambodia
info.players.Myanmar
info.players.Mongolia
info.players.Chile
info.players.Mexico
info.players.Costa Rica
info.players.Ivory Coast
info.players.Suriname
info.players.Turks and Caicos Island
info.players.Timor-Leste
info.players.Zambia
info.supersubs.New Zealand
info.supersubs.South Africa
info.bowl_out
info.outcome.bowl_out

In [23]:
final_df['info.players.Australia']

0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
                              ...
5322                                                  NaN
5323                                                  NaN
5324                                                  NaN
5325    [GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...
5326    [DA Warner, GJ Maxwell, MC Henriques, JP Faulk...
Name: info.players.Australia, Length: 5327, dtype: object

In [24]:
player_cols = [col for col in final_df.columns
               if 'info.players.' in col]

print("Matching columns:", len(player_cols))
player_cols[:20]

Matching columns: 108

['info.players.West Indies',
 'info.players.England',
 'info.players.India',
 'info.players.Australia',
 'info.players.New Zealand',
 'info.players.Sri Lanka',
 'info.players.Pakistan',
 'info.players.Hong Kong',
 'info.players.Scotland',
 'info.players.Netherlands',
 'info.players.Oman',
 'info.players.Ireland',
 'info.players.United Arab Emirates',
 'info.players.South Africa',
 'info.players.Bangladesh',
 'info.players.Papua New Guinea',
 'info.players.ICC World XI',
 'info.players.Nepal',
 'info.players.Zimbabwe',
 'info.players.Thailand']

In [25]:
final_df = final_df.drop(columns=player_cols)

In [26]:
final_df.shape

(5327, 30)

In [27]:
final_df.to_pickle("final_df_30cols.pkl")

In [28]:
final_df.columns.tolist()

['innings',
 'meta.data_version',
 'meta.created',
 'meta.revision',
 'info.balls_per_over',
 'info.city',
 'info.dates',
 'info.gender',
 'info.match_type',
 'info.match_type_number',
 'info.outcome.winner',
 'info.outcome.by.runs',
 'info.overs',
 'info.player_of_match',
 'info.teams',
 'info.toss.decision',
 'info.toss.winner',
 'info.umpires',
 'info.venue',
 'match_id',
 'info.outcome.by.wickets',
 'info.neutral_venue',
 'info.outcome.result',
 'info.outcome.method',
 'info.outcome.eliminator',
 'info.toss.uncontested',
 'info.supersubs.New Zealand',
 'info.supersubs.South Africa',
 'info.bowl_out',
 'info.outcome.bowl_out']

In [29]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.bowl_out',
    'info.bowl_out',
    'info.supersubs.South Africa',
    'info.supersubs.New Zealand',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [30]:
final_df

,innings,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.toss.uncontested
0,"[{'1st innings': {'team': 'West Indies', 'deli...",6,Chester-le-Street,[2017-09-16],male,T20,West Indies,20,[SP Narine],"[West Indies, England]",field,England,"[RT Robinson, MA Gough]",Riverside Ground,0,NaN
1,"[{'1st innings': {'team': 'India', 'deliveries...",6,Kanpur,[2017-01-26],male,T20,England,20,[MM Ali],"[India, England]",field,England,"[AK Chaudhary, Nitin Menon]",Green Park,1,NaN
2,"[{'1st innings': {'team': 'India', 'deliveries...",6,Nagpur,[2017-01-29],male,T20,India,20,[JJ Bumrah],"[India, England]",field,England,"[AK Chaudhary, C Shamshuddin]","Vidarbha Cricket Association Stadium, Jamtha",2,NaN
3,"[{'1st innings': {'team': 'India', 'deliveries...",6,Bangalore,[2017-02-01],male,T20,India,20,[YS Chahal],"[India, England]",field,England,"[AK Chaudhary, Nitin Menon]",M Chinnaswamy Stadium,3,NaN
4,"[{'1st innings': {'team': 'West Indies', 'deli...",6,Lauderhill,[2016-08-27],male,T20,West Indies,20,[E Lewis],"[India, West Indies]",field,India,"[N Duguid, JS Wilson]",Central Broward Regional Park Stadium Turf Ground,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5322,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Mirpur,[2016-03-04],male,T20,Pakistan,20,[Umar Akmal],"[Pakistan, Sri Lanka]",field,Pakistan,"[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,5322,NaN
5323,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,Mirpur,[2016-03-06],male,T20,India,20,[S Dhawan],"[Bangladesh, India]",field,India,"[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,5323,NaN
5324,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,Dubai,[2016-02-03],male,T20,Netherlands,20,[Mudassar Bukhari],"[United Arab Emirates, Netherlands]",field,United Arab Emirates,"[CK Nandan, Sarika Prasad]",ICC Academy,5324,NaN
5325,"[{'1st innings': {'team': 'Australia', 'delive...",6,NaN,[2016-09-06],male,T20,Australia,20,[GJ Maxwell],"[Sri Lanka, Australia]",field,Sri Lanka,"[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,5325,NaN
5326,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Colombo,[2016-09-09],male,T20,Australia,20,[GJ Maxwell],"[Sri Lanka, Australia]",bat,Sri Lanka,"[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,5326,NaN

In [31]:
final_df['info.gender'].value_counts()

info.gender
male      3352
female    1975
Name: count, dtype: int64

In [32]:
final_df = final_df[final_df['info.gender'] == 'male']
final_df.drop(columns=['info.gender'],inplace=True)
final_df

C:\Users\KASHIF\AppData\Local\Temp\ipykernel_25464\2142223783.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.gender'],inplace=True)

,innings,info.balls_per_over,info.city,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.toss.uncontested
0,"[{'1st innings': {'team': 'West Indies', 'deli...",6,Chester-le-Street,[2017-09-16],T20,West Indies,20,[SP Narine],"[West Indies, England]",field,England,"[RT Robinson, MA Gough]",Riverside Ground,0,NaN
1,"[{'1st innings': {'team': 'India', 'deliveries...",6,Kanpur,[2017-01-26],T20,England,20,[MM Ali],"[India, England]",field,England,"[AK Chaudhary, Nitin Menon]",Green Park,1,NaN
2,"[{'1st innings': {'team': 'India', 'deliveries...",6,Nagpur,[2017-01-29],T20,India,20,[JJ Bumrah],"[India, England]",field,England,"[AK Chaudhary, C Shamshuddin]","Vidarbha Cricket Association Stadium, Jamtha",2,NaN
3,"[{'1st innings': {'team': 'India', 'deliveries...",6,Bangalore,[2017-02-01],T20,India,20,[YS Chahal],"[India, England]",field,England,"[AK Chaudhary, Nitin Menon]",M Chinnaswamy Stadium,3,NaN
4,"[{'1st innings': {'team': 'West Indies', 'deli...",6,Lauderhill,[2016-08-27],T20,West Indies,20,[E Lewis],"[India, West Indies]",field,India,"[N Duguid, JS Wilson]",Central Broward Regional Park Stadium Turf Ground,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5322,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Mirpur,[2016-03-04],T20,Pakistan,20,[Umar Akmal],"[Pakistan, Sri Lanka]",field,Pakistan,"[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,5322,NaN
5323,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,Mirpur,[2016-03-06],T20,India,20,[S Dhawan],"[Bangladesh, India]",field,India,"[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,5323,NaN
5324,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,Dubai,[2016-02-03],T20,Netherlands,20,[Mudassar Bukhari],"[United Arab Emirates, Netherlands]",field,United Arab Emirates,"[CK Nandan, Sarika Prasad]",ICC Academy,5324,NaN
5325,"[{'1st innings': {'team': 'Australia', 'delive...",6,NaN,[2016-09-06],T20,Australia,20,[GJ Maxwell],"[Sri Lanka, Australia]",field,Sri Lanka,"[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,5325,NaN
5326,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Colombo,[2016-09-09],T20,Australia,20,[GJ Maxwell],"[Sri Lanka, Australia]",bat,Sri Lanka,"[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,5326,NaN

In [33]:
final_df['info.match_type'].value_counts()

info.match_type
T20    3352
Name: count, dtype: int64

In [34]:
final_df['info.overs'].value_counts()

info.overs
20    3344
50       8
Name: count, dtype: int64

In [35]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
final_df

C:\Users\KASHIF\AppData\Local\Temp\ipykernel_25464\3157072726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.overs','info.match_type'],inplace=True)

,innings,info.balls_per_over,info.city,info.dates,info.outcome.winner,info.player_of_match,info.teams,info.toss.decision,info.toss.winner,info.umpires,info.venue,match_id,info.toss.uncontested
0,"[{'1st innings': {'team': 'West Indies', 'deli...",6,Chester-le-Street,[2017-09-16],West Indies,[SP Narine],"[West Indies, England]",field,England,"[RT Robinson, MA Gough]",Riverside Ground,0,NaN
1,"[{'1st innings': {'team': 'India', 'deliveries...",6,Kanpur,[2017-01-26],England,[MM Ali],"[India, England]",field,England,"[AK Chaudhary, Nitin Menon]",Green Park,1,NaN
2,"[{'1st innings': {'team': 'India', 'deliveries...",6,Nagpur,[2017-01-29],India,[JJ Bumrah],"[India, England]",field,England,"[AK Chaudhary, C Shamshuddin]","Vidarbha Cricket Association Stadium, Jamtha",2,NaN
3,"[{'1st innings': {'team': 'India', 'deliveries...",6,Bangalore,[2017-02-01],India,[YS Chahal],"[India, England]",field,England,"[AK Chaudhary, Nitin Menon]",M Chinnaswamy Stadium,3,NaN
4,"[{'1st innings': {'team': 'West Indies', 'deli...",6,Lauderhill,[2016-08-27],West Indies,[E Lewis],"[India, West Indies]",field,India,"[N Duguid, JS Wilson]",Central Broward Regional Park Stadium Turf Ground,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5322,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Mirpur,[2016-03-04],Pakistan,[Umar Akmal],"[Pakistan, Sri Lanka]",field,Pakistan,"[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,5322,NaN
5323,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,Mirpur,[2016-03-06],India,[S Dhawan],"[Bangladesh, India]",field,India,"[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,5323,NaN
5324,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,Dubai,[2016-02-03],Netherlands,[Mudassar Bukhari],"[United Arab Emirates, Netherlands]",field,United Arab Emirates,"[CK Nandan, Sarika Prasad]",ICC Academy,5324,NaN
5325,"[{'1st innings': {'team': 'Australia', 'delive...",6,NaN,[2016-09-06],Australia,[GJ Maxwell],"[Sri Lanka, Australia]",field,Sri Lanka,"[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,5325,NaN
5326,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Colombo,[2016-09-09],Australia,[GJ Maxwell],"[Sri Lanka, Australia]",bat,Sri Lanka,"[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,5326,NaN

In [36]:
import pickle
pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [37]:
matches = pickle.load(open('dataset_level1.pkl','rb'))

In [38]:
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'CH Gayle'}},
 {0.2: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {0.3: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CH Gayle'}},
 {0.4: {'non_striker': 'CH Gayle',
   'bowler': 'DJ Willey',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'E Lewis'}},
 {0.5: {'non_striker': 'CH Gayle',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {0.6: {'non_striker': 'CH Gayle',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {0.7: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {1.1: {'non_striker': 'CH Gayle',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {1.2: {'non_striker': 'CH Gayle',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {1.3: {'non_striker': 'CH Gayle',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {1.4: {'non_striker': 'CH Gayle',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'E Lewis'}},
 {1.5: {'non_striker': 'CH Gayle',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {1.6: {'non_striker': 'CH Gayle',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {2.1: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {2.2: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {2.3: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'CH Gayle'}},
 {2.4: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'CH Gayle'}},
 {2.5: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {2.6: {'non_striker': 'E Lewis',
   'bowler': 'DJ Willey',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CH Gayle'}},
 {3.1: {'non_striker': 'E Lewis',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {3.2: {'non_striker': 'E Lewis',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'CH Gayle'}},
 {3.3: {'non_striker': 'E Lewis',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {3.4: {'non_striker': 'E Lewis',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'CH Gayle'}},
 {3.5: {'non_striker': 'E Lewis',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CH Gayle'}},
 {3.6: {'non_striker': 'CH Gayle',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'E Lewis'}},
 {4.1: {'non_striker': 'E Lewis',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CH Gayle'}},
 {4.2: {'non_striker': 'CH Gayle',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'E Lewis'}},
 {4.3: {'non_striker': 'CH Gayle',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {4.4: {'non_striker': 'E Lewis',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'CH Gayle'}},
 {4.5: {'non_striker': 'E Lewis',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {4.6: {'non_striker': 'E Lewis',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'CH Gayle'}},
 {5.1: {'non_striker': 'CH Gayle',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'E Lewis'}},
 {5.2: {'non_striker': 'CH Gayle',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'E Lewis'}},
 {5.3: {'non_striker': 'CH Gayle',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'E Lewis'}},
 {5.4: {'non_striker': 'CH Gayle',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {5.5: {'non_striker': 'CH Gayle',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {5.6: {'non_striker': 'E Lewis',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle'}},
 {6.1: {'non_striker': 'CH Gayle',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'E Lewis'}},
 {6.2: {'non_striker': 'CH Gayle',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {6.3: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CH Gayle',
   'wicket': {'player_out': 'CH Gayle', 'kind': 'run out'}}},
 {6.4: {'non_striker': 'MN Samuels',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {6.5: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MN Samuels'}},
 {6.6: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'MN Samuels'}},
 {6.7: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MN Samuels'}},
 {7.1: {'non_striker': 'E Lewis',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MN Samuels'}},
 {7.2: {'non_striker': 'E Lewis',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MN Samuels'}},
 {7.3: {'non_striker': 'MN Samuels',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'E Lewis'}},
 {7.4: {'non_striker': 'MN Samuels',
   'bowler': 'AU Rashid',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'legbyes': 1},
   'batsman': 'E Lewis'}},
 {7.5: {'non_striker': 'E Lewis',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MN Samuels'}},
 {7.6: {'non_striker': 'MN Samuels',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'E Lewis'}},
 {8.1: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MN Samuels'}},
 {8.2: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MN Samuels'}},
 {8.3: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MN Samuels'}},
 {8.4: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'MN Samuels'}},
 {8.5: {'non_striker': 'E Lewis',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MN Samuels'}},
 {8.6: {'non_striker': 'MN Samuels',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {9.1: {'non_striker': 'MN Samuels',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis'}},
 {9.2: {'non_striker': 'MN Samuels',
   'bowler': 'JE Root',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'E Lewis'}},
 {9.3: {'non_striker': 'MN Samuels',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {9.4: {'non_striker': 'E Lewis',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MN Samuels'}},
 {9.5: {'non_striker': 'MN Samuels',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {9.6: {'non_striker': 'E Lewis',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'MN Samuels'}},
 {9.7: {'non_striker': 'MN Samuels',
   'bowler': 'JE Root',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'E Lewis'}},
 {9.8: {'non_striker': 'MN Samuels',
   'bowler': 'JE Root',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'E Lewis'}},
 {10.1: {'non_striker': 'MN Samuels',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'E Lewis',
   'wicket': {'player_out': 'E Lewis',
    'fielders': ['JE Root'],
    'kind': 'caught'}}},
 {10.2: {'non_striker': 'MN Samuels',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'CAK Walton'}},
 {10.3: {'non_striker': 'MN Samuels',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'CAK Walton'}},
 {10.4: {'non_striker': 'MN Samuels',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CAK Walton'}},
 {10.5: {'non_striker': 'CAK Walton',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'MN Samuels',
   'wicket': {'player_out': 'MN Samuels',
    'fielders': ['JE Root'],
    'kind': 'caught'}}},
 {10.6: {'non_striker': 'CAK Walton',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KA Pollard'}},
 {11.1: {'non_striker': 'CAK Walton',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KA Pollard'}},
 {11.2: {'non_striker': 'CAK Walton',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'KA Pollard'}},
 {11.3: {'non_striker': 'CAK Walton',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KA Pollard'}},
 {11.4: {'non_striker': 'KA Pollard',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CAK Walton'}},
 {11.5: {'non_striker': 'CAK Walton',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KA Pollard'}},
 {11.6: {'non_striker': 'CAK Walton',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KA Pollard'}},
 {12.1: {'non_striker': 'KA Pollard',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CAK Walton'}},
 {12.2: {'non_striker': 'CAK Walton',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'KA Pollard',
   'wicket': {'player_out': 'KA Pollard',
    'fielders': ['TK Curran'],
    'kind': 'caught'}}},
 {12.3: {'non_striker': 'CAK Walton',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'R Powell'}},
 {12.4: {'non_striker': 'CAK Walton',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'R Powell'}},
 {12.5: {'non_striker': 'CAK Walton',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {12.6: {'non_striker': 'R Powell',
   'bowler': 'LE Plunkett',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CAK Walton'}},
 {13.1: {'non_striker': 'R Powell',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CAK Walton'}},
 {13.2: {'non_striker': 'CAK Walton',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'R Powell'}},
 {13.3: {'non_striker': 'CAK Walton',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {13.4: {'non_striker': 'R Powell',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CAK Walton',
   'wicket': {'player_out': 'CAK Walton',
    'fielders': ['DJ Willey'],
    'kind': 'caught'}}},
 {13.5: {'non_striker': 'CR Brathwaite',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {13.6: {'non_striker': 'R Powell',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CR Brathwaite'}},
 {14.1: {'non_striker': 'CR Brathwaite',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 2, 'batsman': 2},
   'batsman': 'R Powell'}},
 {14.2: {'non_striker': 'CR Brathwaite',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 4, 'batsman': 4},
   'batsman': 'R Powell'}},
 {14.3: {'non_striker': 'CR Brathwaite',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {14.4: {'non_striker': 'R Powell',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CR Brathwaite'}},
 {14.5: {'non_striker': 'CR Brathwaite',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {14.6: {'non_striker': 'R Powell',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'CR Brathwaite'}},
 {15.1: {'non_striker': 'R Powell',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'CR Brathwaite',
   'wicket': {'player_out': 'CR Brathwaite', 'kind': 'bowled'}}},
 {15.2: {'non_striker': 'R Powell',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SP Narine'}},
 {15.3: {'non_striker': 'SP Narine',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {15.4: {'non_striker': 'R Powell',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'SP Narine'}},
 {15.5: {'non_striker': 'SP Narine',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {15.6: {'non_striker': 'R Powell',
   'bowler': 'AU Rashid',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'SP Narine',
   'wicket': {'player_out': 'SP Narine', 'kind': 'lbw'}}},
 {16.1: {'non_striker': 'AR Nurse',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {16.2: {'non_striker': 'R Powell',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AR Nurse'}},
 {16.3: {'non_striker': 'R Powell',
   'bowler': 'TK Curran',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'AR Nurse'}},
 {16.4: {'non_striker': 'R Powell',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AR Nurse'}},
 {16.5: {'non_striker': 'R Powell',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AR Nurse'}},
 {16.6: {'non_striker': 'AR Nurse',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {16.7: {'non_striker': 'R Powell',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AR Nurse'}},
 {17.1: {'non_striker': 'R Powell',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'AR Nurse'}},
 {17.2: {'non_striker': 'R Powell',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AR Nurse'}},
 {17.3: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 1, 'total': 1, 'batsman': 0},
   'extras': {'wides': 1},
   'batsman': 'R Powell'}},
 {17.4: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'R Powell'}},
 {17.5: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'R Powell'}},
 {17.6: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'R Powell'}},
 {17.7: {'non_striker': 'R Powell',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AR Nurse'}},
 {17.8: {'non_striker': 'R Powell',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AR Nurse'}},
 {18.1: {'non_striker': 'R Powell',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AR Nurse'}},
 {18.2: {'non_striker': 'AR Nurse',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'R Powell'}},
 {18.3: {'non_striker': 'AR Nurse',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'R Powell',
   'wicket': {'player_out': 'R Powell',
    'fielders': ['CJ Jordan'],
    'kind': 'caught'}}},
 {18.4: {'non_striker': 'JE Taylor',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AR Nurse'}},
 {18.5: {'non_striker': 'AR Nurse',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'JE Taylor'}},
 {18.6: {'non_striker': 'JE Taylor',
   'bowler': 'TK Curran',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'AR Nurse'}},
 {19.1: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JE Taylor'}},
 {19.2: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 0, 'batsman': 0},
   'batsman': 'JE Taylor',
   'wicket': {'player_out': 'JE Taylor', 'kind': 'lbw'}}},
 {19.3: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KOK Williams'}},
 {19.4: {'non_striker': 'KOK Williams',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 6, 'batsman': 6},
   'batsman': 'AR Nurse'}},
 {19.5: {'non_striker': 'KOK Williams',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'AR Nurse'}},
 {19.6: {'non_striker': 'AR Nurse',
   'bowler': 'CJ Jordan',
   'runs': {'extras': 0, 'total': 1, 'batsman': 1},
   'batsman': 'KOK Williams'}}]

In [45]:
count = 0
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df = pd.concat([delivery_df, loop_df], ignore_index=True)

In [46]:
delivery_df.shape

(402731, 10)

In [47]:
delivery_df.to_pickle("delivery_df.pkl")

In [48]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [49]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis = 1)

In [50]:
delivery_df.drop(columns = ['teams'], inplace = True)

In [51]:
delivery_df.head()

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,1,West Indies,0.1,CH Gayle,DJ Willey,4,0,Chester-le-Street,Riverside Ground,England
1,1,West Indies,0.2,CH Gayle,DJ Willey,0,0,Chester-le-Street,Riverside Ground,England
2,1,West Indies,0.3,CH Gayle,DJ Willey,1,0,Chester-le-Street,Riverside Ground,England
3,1,West Indies,0.4,E Lewis,DJ Willey,1,0,Chester-le-Street,Riverside Ground,England
4,1,West Indies,0.5,E Lewis,DJ Willey,0,0,Chester-le-Street,Riverside Ground,England

In [52]:
delivery_df['batting_team'].unique()

array(['West Indies', 'India', 'Pakistan', 'New Zealand', 'England',
       'Scotland', 'Oman', 'Hong Kong', 'Ireland', 'South Africa',
       'Bangladesh', 'Papua New Guinea', 'United Arab Emirates',
       'Sri Lanka', 'Australia', 'Netherlands', 'Zimbabwe', 'Nepal',
       'Vanuatu', 'United States of America', 'Germany', 'Ghana',
       'Uganda', 'Kenya', 'Namibia', 'Nigeria', 'Botswana', 'Guernsey',
       'Denmark', 'Jersey', 'Italy', 'Norway', 'Thailand', 'Malaysia',
       'Maldives', 'Singapore', 'Kuwait', 'Bermuda', 'Canada',
       'Cayman Islands', 'Portugal', 'Gibraltar', 'Spain', 'Bhutan',
       'Iran', 'Belgium', 'Isle of Man', 'Bulgaria', 'Romania',
       'Luxembourg', 'Austria', 'Czech Republic', 'Greece', 'Serbia',
       'Malta', 'France', 'Sweden', 'Rwanda', 'Finland', 'Hungary',
       'Estonia', 'Cyprus', 'Switzerland', 'Seychelles', 'Malawi',
       'Lesotho', 'Swaziland', 'Tanzania', 'Mozambique', 'Sierra Leone',
       'Cameroon', 'Bahrain', 'Qatar', 'Belize', 'Bahamas', 'Argentina',
       'Panama', 'Philippines', 'Israel', 'Croatia', 'Turkey', 'Slovenia',
       'Cook Islands', 'Samoa', 'Fiji', 'Japan', 'Indonesia',
       'South Korea', 'Mali', 'St Helena', 'Gambia', 'Eswatini',
       'Saudi Arabia', 'China', 'Myanmar', 'Chile', 'Mexico', 'Cambodia',
       'Costa Rica', 'Mongolia', 'Brazil', 'Ivory Coast', 'Suriname',
       'Turks and Caicos Island', 'Timor-Leste', 'Zambia'], dtype=object)

In [53]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [54]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [55]:
delivery_df.shape

(110049, 10)

In [56]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,1,West Indies,0.1,CH Gayle,DJ Willey,4,0,Chester-le-Street,Riverside Ground,England
1,1,West Indies,0.2,CH Gayle,DJ Willey,0,0,Chester-le-Street,Riverside Ground,England
2,1,West Indies,0.3,CH Gayle,DJ Willey,1,0,Chester-le-Street,Riverside Ground,England
3,1,West Indies,0.4,E Lewis,DJ Willey,1,0,Chester-le-Street,Riverside Ground,England
4,1,West Indies,0.5,E Lewis,DJ Willey,0,0,Chester-le-Street,Riverside Ground,England
...,...,...,...,...,...,...,...,...,...,...
402726,3344,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
402727,3344,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
402728,3344,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
402729,3344,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
402730,3344,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [57]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [58]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,1,West Indies,England,0.1,4,0,Chester-le-Street,Riverside Ground
1,1,West Indies,England,0.2,0,0,Chester-le-Street,Riverside Ground
2,1,West Indies,England,0.3,1,0,Chester-le-Street,Riverside Ground
3,1,West Indies,England,0.4,1,0,Chester-le-Street,Riverside Ground
4,1,West Indies,England,0.5,0,0,Chester-le-Street,Riverside Ground
...,...,...,...,...,...,...,...,...
402726,3344,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
402727,3344,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
402728,3344,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
402729,3344,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
402730,3344,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [60]:
pickle.dump(output,open('dataset_level2.pkl','wb'))

In [1]:
teams

NameError: name 'teams' is not defined