In [130]:
import pandas as pd
import pickle
import numpy as np

In [131]:
df = pickle.load(open('dataset_level2.pkl','rb'))

In [132]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,1,West Indies,England,0.1,4,0,Chester-le-Street,Riverside Ground
1,1,West Indies,England,0.2,0,0,Chester-le-Street,Riverside Ground
2,1,West Indies,England,0.3,1,0,Chester-le-Street,Riverside Ground
3,1,West Indies,England,0.4,1,0,Chester-le-Street,Riverside Ground
4,1,West Indies,England,0.5,0,0,Chester-le-Street,Riverside Ground
...,...,...,...,...,...,...,...,...
402726,3344,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
402727,3344,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
402728,3344,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
402729,3344,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
402730,3344,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [133]:
#we need bowling team
#batting team
#city
#current score
#ball left
#last 5 over
#crr
#wickets left

In [134]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8171
venue                  0
dtype: int64

In [135]:
df.shape

(110049, 8)

In [136]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1328
Sydney Cricket Ground                       621
Adelaide Oval                               373
Harare Sports Club                          372
Sylhet International Cricket Stadium        128
Sharjah Cricket Stadium                     127
Carrara Oval                                 64
Name: count, dtype: int64

In [137]:
cities = np.where(df['city'].isnull(),df['venue'].str.split().apply(lambda x : x[0]),df['city'])

In [138]:
df['city'] = cities

In [139]:
df['city'].isnull().sum()

np.int64(0)

In [140]:
df.drop(columns = ['venue'], inplace = True)

In [141]:
eligible_cities= df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [142]:
df[df['city'].isin(eligible_cities)]

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,1,West Indies,England,0.1,4,0,Chester-le-Street
1,1,West Indies,England,0.2,0,0,Chester-le-Street
2,1,West Indies,England,0.3,1,0,Chester-le-Street
3,1,West Indies,England,0.4,1,0,Chester-le-Street
4,1,West Indies,England,0.5,0,0,Chester-le-Street
...,...,...,...,...,...,...,...
402726,3344,Sri Lanka,Australia,19.3,1,0,Colombo
402727,3344,Sri Lanka,Australia,19.4,0,0,Colombo
402728,3344,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
402729,3344,Sri Lanka,Australia,19.6,2,0,Colombo
402730,3344,Sri Lanka,Australia,19.7,1,0,Colombo

In [143]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,1,West Indies,England,0.1,4,0,Chester-le-Street
1,1,West Indies,England,0.2,0,0,Chester-le-Street
2,1,West Indies,England,0.3,1,0,Chester-le-Street
3,1,West Indies,England,0.4,1,0,Chester-le-Street
4,1,West Indies,England,0.5,0,0,Chester-le-Street
...,...,...,...,...,...,...,...
402726,3344,Sri Lanka,Australia,19.3,1,0,Colombo
402727,3344,Sri Lanka,Australia,19.4,0,0,Colombo
402728,3344,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
402729,3344,Sri Lanka,Australia,19.6,2,0,Colombo
402730,3344,Sri Lanka,Australia,19.7,1,0,Colombo

In [144]:
df.sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
158820,1323,New Zealand,Pakistan,18.6,2,0,Hamilton

In [145]:
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [146]:
df.iloc[0:125,:]

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
0,1,West Indies,England,0.1,4,0,Chester-le-Street,4
1,1,West Indies,England,0.2,0,0,Chester-le-Street,4
2,1,West Indies,England,0.3,1,0,Chester-le-Street,5
3,1,West Indies,England,0.4,1,0,Chester-le-Street,6
4,1,West Indies,England,0.5,0,0,Chester-le-Street,6
...,...,...,...,...,...,...,...,...
120,1,West Indies,England,18.6,0,0,Chester-le-Street,167
121,1,West Indies,England,19.1,0,0,Chester-le-Street,167
122,1,West Indies,England,19.2,0,JE Taylor,Chester-le-Street,167
123,1,West Indies,England,19.3,1,0,Chester-le-Street,168
124,1,West Indies,England,19.4,6,0,Chester-le-Street,174

In [147]:
df['over'] = df['ball'].apply(lambda x : str(x).split('.')[0])
df['ball_no'] = df['ball'].apply(lambda x : str(x).split('.')[1])

In [148]:
df['balls_bowled'] = (df['over'].astype(int) * 6) + df['ball_no'].astype(int)

In [149]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x : 0 if x < 0 else x)

In [150]:
df.sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
14142,118,New Zealand,India,18.5,1,0,Auckland,150,18,5,113,7

In [151]:
df[df['balls_bowled'] > 120].sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
384975,3196,Australia,West Indies,19.7,1,0,Mirpur,173,19,7,121,0

In [152]:
print(df['player_dismissed'].unique())

['0' 'CH Gayle' 'E Lewis' 'MN Samuels' 'KA Pollard' 'CAK Walton'
 'CR Brathwaite' 'SP Narine' 'R Powell' 'JE Taylor' 'KL Rahul' 'V Kohli'
 'Yuvraj Singh' 'SK Raina' 'MK Pandey' 'HH Pandya' 'Parvez Rasool'
 'A Mishra' 'MS Dhoni' 'J Charles' 'AD Russell' 'LMP Simmons'
 'ADS Fletcher' 'DJ Bravo' 'S Badree' 'N Pooran' 'Sharjeel Khan'
 'Babar Azam' 'Khalid Latif' 'Shoaib Malik' 'C Munro' 'MJ Guptill'
 'TC Bruce' 'KS Williamson' 'TA Blundell' 'LRPL Taylor' 'MJ Santner'
 'TG Southee' 'IS Sodhi' 'JJ Roy' 'AD Hales' 'EJG Morgan' 'JC Buttler'
 'SW Billings' 'DJ Malan' 'DJ Willey' 'AU Rashid' 'TK Curran' 'JM Vince'
 'C de Grandhomme' 'MS Chapman' 'TL Seifert' 'LA Dawson' 'HM Amla'
 'AB de Villiers' 'JP Duminy' 'Q de Kock' 'M Mosehle' 'JO Holder'
 'Kamran Akmal' 'Ahmed Shehzad' 'Fakhar Zaman' 'Sarfraz Ahmed'
 'Sohail Tanvir' 'Imad Wasim' 'Wahab Riaz' 'Shadab Khan' 'Tamim Iqbal'
 'Sabbir Rahman' 'Soumya Sarkar' 'Mushfiqur Rahim' 'Shakib Al Hasan'
 'Mahmudullah' 'Imrul Kayes' 'Mosaddek Hossain' 'Mashrafe Mortaza'
 'Mehedi Hasan Miraz' 'Mohammad Saifuddin' 'JN Mohammed' 'S Dhawan'
 'KD Karthik' 'RR Pant' 'KM Jadhav' 'WU Tharanga' 'N Dickwella'
 'AD Mathews' 'EMDY Munaweera' 'NLTC Perera' 'MD Shanaka' 'S Prasanna'
 'GD Phillips' 'AK Kitchen' 'DAJ Bracewell' 'Umar Amin'
 'Mohammad Nawaz (3)' 'Haris Sohail' 'Faheem Ashraf' 'Hasan Ali'
 'Mohammad Amir' 'DA Warner' 'GJ Maxwell' 'AJ Finch' 'MC Henriques'
 'TM Head' 'TD Paine' 'NM Coulter-Nile' 'DT Christian' 'RG Sharma'
 'B Kumar' 'JJ Bumrah' 'Kuldeep Yadav' 'JE Root' 'JM Bairstow' 'MM Ali'
 'CJ Jordan' 'BA Stokes' 'LE Plunkett' 'SS Iyer' 'MD Gunathilaka'
 'S Samarawickrama' 'SMA Priyanjan' 'ML Udawatte' 'SS Pathirana' 'I Udana'
 'JRMVB Sanjaya' 'MDKJ Perera' 'DAS Gunaratne' 'Zakir Hasan'
 'Afif Hossain' 'BKG Mendis' 'Liton Das' 'Rubel Hossain' 'LD Chandimal'
 'BMAJ Mendis' 'A Dananjaya' 'PVD Chameera' 'Hussain Talat' 'Asif Ali'
 'AM McCarthy' 'JL Denly' 'RR Hendricks' 'H Klaasen' 'AL Phehlukwayo'
 'K Rabada' 'DA Miller' 'L Ngidi' 'T Shamsi' 'Mohammad Hafeez'
 'MP Stoinis' 'DJM Short' 'AT Carey' 'AC Agar' 'AJ Tye' 'GL Cloete'
 'F du Plessis' 'HE van der Dussen' 'CH Morris' 'JN Malan'
 'Mohammad Rizwan' 'WIA Fernando' 'AK Perera' 'PHKD Mendis' 'DM de Silva'
 'AK Markram' 'CA Lynn' 'Ariful Haque' 'Nazmul Islam' 'Imam-ul-Haq'
 'Mustafizur Rahman' 'SD Hope' 'KMA Paul' 'SO Hetmyer' 'FA Allen'
 'SE Rutherford' 'O Thomas' 'DJ Mitchell' 'HM Nicholls' 'Sahibzada Farhan'
 'D Ramdin' 'DM Bravo' 'JD Campbell' 'SS Cottrell' 'OC McCoy' 'KH Pandya'
 'UT Yadav' 'PWH de Silva' 'SL Malinga' 'PADLR Sandakan' 'BOP Fernando'
 'GSNFG Jayasuriya' 'Khushdil Shah' 'Iftikhar Ahmed' 'T Bavuma' 'JT Smuts'
 'D Pretorius' 'BE Hendricks' 'MS Wade' 'SPD Smith' 'MR Marsh' 'RA Jadeja'
 'Washington Sundar' 'S Dube' 'Mohammad Naim' 'BA King' 'JDS Neesham'
 'T Banton' 'SV Samson' 'SN Thakur' 'YS Chahal' 'LD Madushanka'
 'L Gregory' 'Haider Ali' 'PBB Rajapaksa' 'M Bhanuka' 'Mahedi Hasan'
 'Abdullah Shafique' 'SC Kuggeleijn' 'DP Conway' 'JR Philippe'
 'JA Richardson' 'FH Allen' 'WA Young' 'GF Linde' 'Sohaib Maqsood'
 'LS Livingstone' 'MW Parkinson' 'PJ van Biljon' 'BC Fortuin'
 'Ishan Kishan' 'SA Yadav' 'WJ Lubbe' 'Usman Qadir' 'PWA Mulder'
 'SSB Magala' 'P Nissanka' 'KNA Bandara' 'S Mahmood' 'PD Salt' 'KR Mayers'
 'R Shepherd' 'PP Shaw' 'RD Gaikwad' 'D Padikkal' 'N Rana' 'RD Chahar'
 'CV Varun' 'A Nortje' 'AJ Turner' 'JP Inglis' 'BR McDermott' 'MA Starc'
 'PJ Cummins' 'KIC Asalanka' 'C Karunaratne' 'M Theekshana' 'DR Sams'
 'Nurul Hasan' 'Shamim Hossain' 'Shoriful Islam' 'R Ravindra' 'TWM Latham'
 'CE McConchie' 'AY Patel' 'JA Duffy' 'BM Tickner' 'KA Maharaj'
 'R Rampaul' 'HR Walsh' 'RL Chase' 'CBRLS Kumara' 'A Zampa' 'Taskin Ahmed'
 'Nasum Ahmed' 'DJ Hooda' 'AR Patel' 'HV Patel' 'HC Brook' 'RR Rossouw'
 'T Stubbs' 'Saif Hassan' 'Nazmul Hossain Shanto' 'Aminul Islam' 'VR Iyer'
 'AJ Hosein' 'OF Smith' 'K Mishara' 'J Liyanage' 'Mohammad Nawaz'
 'Mohammad Wasim' 'SSJ Brooks' 'Shaheen Shah Afridi' 'R Ashwin'
 'Mohammed Shami' 'Mohammad Haris' 'Shan Masood' 'Haris Rauf'
 'Munim Shahriar' 'Anamul Haque' 'RA Reifer' 'AS Joseph' 'C Green'
 'TH David' 'SM Curran' 'Avesh Khan' 'AF Milne' 'MG Bracewell'
 'Yasir Ali Chowdhury' 'PM Liyanagamage' 'D Madushanka' 'Naseem Shah'
 'BM Duckett' 'WG Jacks' 'Aamer Jamal' 'Shahnawaz Dhani' 'WD Parnell'
 'Rehan Ahmed' 'Saim Ayub' 'CJ Bowes' 'Shubman Gill' 'RA Tripathi'
 'LH Ferguson' 'CR Woakes' 'JC Archer' 'Rony Talukdar' 'MW Short'
 'AM Hardie' 'D Brevis' 'G Coetzee' 'MP Breetzke' 'D Ferreira' 'TS Mills'
 'SA Abbott' 'Tilak Varma' 'YBK Jaiswal' 'Arshdeep Singh' 'Azam Khan'
 'Usman Khan' 'XC Bartlett' 'J Fraser-McGurk' 'JM Sharma' 'RK Singh'
 'Towhid Hridoy' 'Tanvir Islam' 'Rishad Hossain' 'Haseebullah Khan'
 'JR Hazlewood' 'DL Chahar' 'Ravi Bishnoi' 'Mahmudul Hasan Joy'
 'Parvez Hossain Emon' 'Shahadat Hossain' 'Mrittunjoy Chowdhury'
 'Rakibul Hasan' 'R Mondol' 'M Pathirana' 'N Thushara' 'Tanzid Hasan'
 'M Jansen' 'TB Robinson' 'D Foxcroft' 'BV Sears' 'BG Lister'
 'JA Clarkson' 'SH Johnson' 'Agha Salman' 'Irfan Khan' 'Abbas Afridi'
 'Jahandad Khan' 'Sufiyan Muqeem' 'A Simelane' 'N Peter' 'Tayyab Tahir'
 'MW Forde' 'G Motie' 'RD Rickelton' 'PE Kruger' 'A Athanaze' 'Jaker Ali'
 'Tanzim Hasan Sakib' 'Abhishek Sharma' 'Nithish Kumar Reddy' 'R Parag'
 'JG Bethell' 'J Overton' 'AAP Atkinson' 'MA Wood' 'JL Smith' 'BA Carse'
 'RTM Mendis' 'Mohammed Siraj' 'MJ Hay' 'ZGF Foulkes' 'Hassan Nawaz'
 'Abdul Samad' 'Abrar Ahmed' 'KA Jamieson' 'Omair Yousuf' 'LG Pretorius'
 'Ramandeep Singh' 'KU Carty' 'RA Herman' 'S Muthusamy' 'MJ Owen'
 'BJ Dwarshuis' 'NT Ellis' 'C Bosch' 'Harshit Rana' 'OEG Baartman'
 'JDF Vandersay' 'MJ Henry' 'BJ Jacobs' 'JM Cox' 'AWJ Auguste'
 'JNT Seales' 'NF Kelly' 'C Esterhuizen' 'T de Zorzi' 'JF Smith'
 'D Forrester' 'Salman Mirza' 'LB Williams' 'N Burger' 'P Rathnayake'
 'K Pierre' 'C Connolly' 'Khawaja Nafay' 'D Cleaver' 'KD Clarke'
 'GO Jones' 'A Flintoff' 'KP Pietersen' 'MP Vaughan' 'ME Trescothick'
 'AJ Strauss' 'VS Solanki' 'PD Collingwood' 'MJ Clarke' 'AC Gilchrist'
 'A Symonds' 'DR Martyn' 'SM Katich' 'GC Smith' 'JH Kallis' 'HH Gibbs'
 'JM Kemp' 'SM Pollock' 'MV Boucher' 'AG Prince' 'CK Langeveldt'
 'JA Morkel' 'M Ntini' 'IR Bell' 'JWM Dalrymple' 'CMW Read'
 'DPMD Jayawardene' 'ST Jayasuriya' 'TM Dilshan' 'RP Arnold'
 'KC Sangakkara' 'MF Maharoof' 'CK Kapugedera' 'CRD Fernando' 'JR Hopes'
 'RT Ponting' 'RS Morton' 'DR Smith' 'D Ganga' 'WW Hinds' 'S Chanderpaul'
 'LE Bosman' 'JJ van der Wath' 'ML Hayden' 'MEK Hussey' 'SP Fleming'
 'BB McCullum' 'JEC Franklin' 'JAH Marshall' 'NJ Astle' 'PD McGlashan'
 'SE Bond' 'MS Atapattu' 'HMCM Bandara' 'LPC Silva' 'RJ Peterson'
 'T Henderson' 'DS Smith' 'DJG Sammy' 'ACL Richards' 'RR Sarwan'
 'MJ Prior' 'LJ Wright' 'DL Maddy' 'OA Shah' 'CP Schofield'
 'AD Mascarenhas' 'SCJ Broad' 'G Gambhir' 'V Sehwag' 'RV Uthappa'
 'IK Pathan' 'Harbhajan Singh' 'AB Agarkar' 'L Vincent' 'PG Fulton'
 'SB Styris' 'CD McMillan' 'DL Vettori' 'Nazimuddin' 'Mohammad Ashraful'
 'Aftab Ahmed' 'Alok Kapali' 'Farhad Reza' 'Syed Rasel' 'JDP Oram'
 'JS Patel' 'VD Philander' 'Imran Nazir' 'Salman Butt' 'Younis Khan'
 'Shahid Afridi' 'MR Gillespie' 'BJ Hodge' 'NL McCullum' 'J Mubarak'
 'WPUJC Vaas' 'Junaid Siddique' 'Nadif Chowdhury' 'Abdur Razzak'
 'YK Pathan' 'AC Voges' 'LA Pomersbach' 'AA Noffke' 'P Kumar'
 'S Sreesanth' 'JM How' 'DR Flynn' 'KD Mills' 'MJ Mason' 'GJ Hopkins'
 'RN Lewis' 'P Mustard' 'Misbah-ul-Haq' 'MN van Wyk' 'GH Bodi' 'L Ronchi'
 'SE Marsh' 'DJ Hussey' 'SR Watson' 'CL White' 'JL Ontong' 'J Botha'
 'BJ Haddin' 'MG Johnson' 'RE van der Merwe' 'NW Bracken'
 'VB van Jaarsveld' 'CJ Ferguson' 'RS Bopara' 'SM Davies' 'GJ Batty'
 'A Khan' 'B Lee' 'NM Hauritz' 'JS Foster' 'GP Swann' 'JM Anderson'
 'KMDN Kulasekara' 'AJ Redmond' 'Shahzaib Hasan' 'SHT Kandamby'
 'T Thushara' 'Shoaib Khan jnr' 'Fawad Alam' 'JD Ryder' 'AN Cook'
 'IJL Trott' 'MJ North' 'BW Hilfenhaus' 'Naeem Islam' 'Raqibul Hasan'
 'Mehrab Hossain jnr' 'Umar Akmal' 'TR Birt' 'TM Dowlin' 'DP Nannes'
 'SW Tait' 'M Vijay' 'MJ Lumb' 'C Kieswetter' 'Abdul Razzaq' 'TT Bresnan'
 'N Deonarine' 'SJ Benn' 'Shafiul Islam' 'PJ Ingram' 'DR Tuffey'
 'Umar Gul' 'Shoaib Akhtar' 'Mohammad Yousuf' 'CU Jayasinghe'
 'K Weeraratne' 'AN Petersen' 'Imran Farhat' 'JW Hastings' "SNJ O'Keefe"
 'RJ Nicol' 'AJ McKay' 'Zulqarnain Haider' 'Saeed Ajmal' 'Asad Shafiq'
 'SR Patel' 'PA Patel' 'R Dravid' 'AM Rahane' 'MM Patel' 'DP Hyatt'
 'S Badrinath' 'CA Ingram' 'MDK Perera' 'GJ Bailey' 'CJ McKay' 'GB Hogg'
 'XJ Doherty' 'RE Levi' 'MK Tiwary' 'NE Bonner' 'CD Barnwell'
 'DO Christian' 'D Bishoo' 'MC Bascombe' 'Awais Zia' 'AB Barath'
 'Nasir Jamshed' 'Nasir Hossain' 'F Behardien' 'Yasir Arafat'
 'HDRL Thirimanne' 'CS Baugh' 'FH Edwards' 'KS Lokuarachchi' 'PP Chawla'
 'HD Rutherford' 'CJ Anderson' 'RM Hira' 'MJ McClenaghan' 'H Davids'
 'GD Elliott' 'BJ Watling' 'AM Ellis' 'I Sharma' 'JC Tredwell'
 'BCJ Cutting' 'Hammad Azam' 'NJ Maddinson' 'KDK Vithanage' 'AP Devcich'
 'NT Broom' 'JP Faulkner' 'Shamsur Rahman' 'Ziaur Rahman'
 'SMSM Senanayake' 'DW Steyn' 'Arafat Sunny' 'D Wiese' 'KJ Abbott'
 'Anwar Ali' 'Saad Nasim' 'DG Brownlie' 'BR Dunk' 'NJ Reardon' 'R McLaren'
 'GH Worker' 'Mukhtar Ahmed' 'TAM Siriwardana' 'UT Khawaja' 'PM Nevill'
 'AT Rayudu' 'RLB Rambukwella' 'N Pradeep' 'HG Kuhn' 'TB de Bruyn'
 'Imran Tahir' 'AM Phangiso' 'HMRKB Herath' 'Mohammad Mithun'
 'Shuvagata Hom' 'RAS Lakmal' 'A Nehra' 'Khurram Manzoor' 'Mohammad Sami']

In [153]:
temp = df.copy()

In [155]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x: 0 if x == '0' else 1)

In [87]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x : 0 if x == '0' else 1)
#df['player_dismissed'] = df['player_dismissed'].astype(int)
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()
df['wickets_left'] = 10 - df['player_dismissed']

In [129]:
df.iloc[125:300,:]

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
125,1,West Indies,England,19.5,1,1,Chester-le-Street,175,19,5,119,1
126,1,West Indies,England,19.6,1,1,Chester-le-Street,176,19,6,120,0
127,2,India,England,0.1,0,1,Kanpur,0,0,1,1,119
128,2,India,England,0.2,0,1,Kanpur,0,0,2,2,118
129,2,India,England,0.3,4,1,Kanpur,4,0,3,3,117
...,...,...,...,...,...,...,...,...,...,...,...,...
295,3,India,England,6.4,3,1,Nagpur,52,6,4,40,80
296,3,India,England,6.5,1,1,Nagpur,53,6,5,41,79
297,3,India,England,6.6,1,1,Nagpur,54,6,6,42,78
298,3,India,England,6.7,0,1,Nagpur,54,6,7,43,77
299,3,India,England,7.1,1,1,Nagpur,55,7,1,43,77

In [154]:
temp.sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
375755,3120,South Africa,New Zealand,18.4,4,0,Port Elizabeth,154,18,4,112,8

In [157]:
df['player_dismissed'].value_counts()

player_dismissed
0    104107
1      5942
Name: count, dtype: int64

In [158]:
df.groupby('match_id')['player_dismissed'].sum().sort_values(ascending=False).head(20)

match_id
1817    10
2472    10
1985    10
1986    10
2120    10
2151    10
2155    10
157     10
2169    10
132     10
2344    10
2345    10
2350    10
2351    10
2447    10
2480    10
1788    10
2528    10
2545    10
116     10
Name: player_dismissed, dtype: int64

In [159]:
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()

In [163]:
df.sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
183688,1530,India,Bangladesh,15.3,1,4,North Sound,137,15,3,93,27

In [164]:
df['wickets_left'] = 10 - df['player_dismissed']

In [167]:
df.sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left
371799,3086,West Indies,Sri Lanka,16.2,1,5,Colombo,91,16,2,98,22,5

In [168]:
df['crr'] = (df['current_score'] * 6) / df['balls_bowled']

In [169]:
df.sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr
393448,3266,India,South Africa,8.5,1,4,Cuttack,46,8,5,53,67,6,5.207547

In [170]:
groups = df.groupby('match_id')

In [172]:
match_ids = df['match_id'].unique()
last_five = []

for match_id in match_ids:
    temp = groups.get_group(match_id)['runs'].rolling(window=30).sum()
    last_five.extend(temp.tolist())

In [174]:
df['last_five'] = last_five

In [175]:
df.sample()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr,last_five
8536,70,Bangladesh,India,17.2,0,6,Colombo,119,17,2,104,16,4,6.865385,30.0

In [ ]:
#df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five']]

In [179]:
fdf = df.groupby('match_id')['runs'].sum().reset_index().merge(df,on = 'match_id')

In [180]:
fdf.sample()

,match_id,runs_x,batting_team,bowling_team,ball,runs_y,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr,last_five,final_score
39298,981,166,Pakistan,England,16.5,1,1,Karachi,136,16,5,101,19,9,8.079208,38.0,NaN

In [181]:
final_df = fdf[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [182]:
final_df.sample()

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
18098,Bangladesh,Pakistan,Lahore,117,14,6,6.622642,38.0,136

In [184]:
final_df.dropna(inplace = True)

C:\Users\KASHIF\AppData\Local\Temp\ipykernel_12760\1587496580.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace = True)

In [185]:
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [186]:
final_df.shape

(83698, 9)

In [187]:
final_df = final_df.sample(final_df.shape[0])

In [188]:
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
49603,West Indies,South Africa,North Sound,117,18,4,6.882353,31.0,135
27681,South Africa,Australia,Abu Dhabi,83,35,4,5.858824,29.0,118
42958,New Zealand,India,Lucknow,93,5,2,4.852174,25.0,99
104062,India,Australia,Melbourne,84,65,10,9.163636,50.0,184
82756,Pakistan,Australia,Birmingham,104,43,5,8.103896,55.0,167
...,...,...,...,...,...,...,...,...,...
9363,Bangladesh,West Indies,Lauderhill,71,85,8,12.171429,65.0,184
91309,West Indies,Australia,Barbados,121,44,6,9.552632,35.0,160
18273,Australia,India,Sydney,55,88,9,10.312500,50.0,194
32526,India,South Africa,Delhi,211,0,6,10.550000,57.0,211
69665,South Africa,Australia,Johannesburg,105,48,9,8.750000,46.0,201

In [198]:
X = final_df.drop(columns = ['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 1)

In [199]:
X.shape

(83698, 8)

In [201]:
y_train.shape

(66958,)

In [202]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error

In [203]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
81519,Pakistan,South Africa,St Lucia,72,51,6,6.260870,50.0
4127,India,Australia,Guwahati,85,29,3,5.604396,24.0
71305,New Zealand,India,Johannesburg,164,13,5,9.196262,71.0
86563,Australia,India,Sydney,81,58,8,7.838710,32.0
73952,England,New Zealand,Christchurch,67,83,9,10.864865,63.0
...,...,...,...,...,...,...,...,...
16457,Sri Lanka,New Zealand,Kandy,50,66,7,5.555556,19.0
64776,South Africa,Pakistan,Lahore,42,78,6,6.000000,29.0
30835,South Africa,England,Southampton,84,56,8,7.875000,31.0
95357,South Africa,Sri Lanka,Hambantota,140,12,8,7.777778,39.0
64633,South Africa,Pakistan,Rawalpindi,54,91,9,11.172414,51.0

In [227]:
trf = ColumnTransformer([
    ('trf', OneHotEncoder(sparse_output= False, drop = 'first'),['batting_team','bowling_team','city'])
],remainder = 'passthrough')

In [228]:
pipe = Pipeline(steps = [
    ('step1', trf),
    ('step2', StandardScaler()),
    ('step3', XGBRegressor(n_estimator = 1000,learning_rate = 0.2,max_depth = 12,random_state = 1))
])

In [229]:
pipe.fit(X_train,y_train)

C:\Users\KASHIF\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [20:09:32] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:793:
Parameters: { "n_estimator" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', StandardScaler()),
                ('step3',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.2,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=12, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimator=1000, n_estimators=None, n_jobs=None, ...))])

In [232]:
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9631258249282837
4.253983020782471

In [233]:
pickle.dump(pipe,open('pipe.pkl','wb'))

In [237]:
len(final_df['bowling_team'].unique())

9

In [238]:
eligibe_cities

NameError: name 'eligibe_cities' is not defined

In [239]:
df['city'].unique()

array(['Chester-le-Street', 'Kanpur', 'Nagpur', 'Bangalore', 'Lauderhill',
       'Dubai', 'Abu Dhabi', 'Sydney', 'Hobart', 'Melbourne',
       'Wellington', 'Auckland', 'Hamilton', 'Bloemfontein',
       'Potchefstroom', 'Barbados', 'Trinidad', 'Colombo', 'Jamaica',
       'Nelson', 'Mount Maunganui', 'Ranchi', 'Guwahati', 'Birmingham',
       'Manchester', 'Cardiff', 'Bristol', 'Delhi', 'Rajkot',
       'Thiruvananthapuram', 'Lahore', 'Johannesburg', 'Centurion',
       'Cape Town', 'Cuttack', 'Indore', 'Mumbai', 'Dhaka', 'Sylhet',
       'Karachi', 'Harare', 'Carrara', 'Brisbane', 'St Kitts', 'Kolkata',
       'Lucknow', 'Chennai', 'Gros Islet', 'Basseterre', 'Visakhapatnam',
       'Bengaluru', 'Adelaide', 'Canberra', 'Perth', 'East London',
       'Durban', 'Port Elizabeth', 'Chandigarh', 'Hyderabad',
       'Christchurch', 'Napier', 'Providence', 'Kandy', 'Southampton',
       'Pune', 'Dunedin', 'Paarl', 'Nottingham', 'Leeds', 'Ahmedabad',
       'Coolidge', 'Bridgetown', "St George's", 'Sharjah', 'Jaipur',
       'Dharamsala', 'Roseau', 'Tarouba', 'Kingston', 'Queenstown',
       'Rawalpindi', 'Chattogram', 'London', 'Gqeberha', 'Raipur',
       'Hangzhou', 'New York', 'Dallas', 'North Sound', 'Kingstown',
       'Gwalior', 'Dambulla', 'Darwin', 'Cairns', 'New Chandigarh',
       'Nairobi', 'King City', 'Guyana', 'St Lucia', 'Antigua',
       'Pallekele', 'Mirpur', 'Hambantota', 'St Vincent', 'Chittagong',
       'Dominica', 'Dharmasala'], dtype=object)

In [240]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
81519,Pakistan,South Africa,St Lucia,72,51,6,6.260870,50.0
4127,India,Australia,Guwahati,85,29,3,5.604396,24.0
71305,New Zealand,India,Johannesburg,164,13,5,9.196262,71.0
86563,Australia,India,Sydney,81,58,8,7.838710,32.0
73952,England,New Zealand,Christchurch,67,83,9,10.864865,63.0
...,...,...,...,...,...,...,...,...
16457,Sri Lanka,New Zealand,Kandy,50,66,7,5.555556,19.0
64776,South Africa,Pakistan,Lahore,42,78,6,6.000000,29.0
30835,South Africa,England,Southampton,84,56,8,7.875000,31.0
95357,South Africa,Sri Lanka,Hambantota,140,12,8,7.777778,39.0
64633,South Africa,Pakistan,Rawalpindi,54,91,9,11.172414,51.0